Rookie.CustomerSite/Components/CategoryMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Rookie.CustomerSite.Containts;
using Rookie.CustomerSite.Services.BaseServices;
using RookieShop.Backend.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace Rookie.CustomerSite.Components
{
    public class CategoryMenuViewComponent: ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {

            HttpResponseMessage Res = await RequestServices.GetAsync(APICategoryEndPoint.GetList);
            if (Res.IsSuccessStatusCode)
            {
                var list = await Res.Content.ReadAsAsync<IEnumerable<Category>>();

                return  View(list.ToList()) ;
            }
            return null;

        }
    }
}

Rookie.CustomerSite/Controllers/ProductController.cs
using IdentityModel.Client;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using Newtonsoft.Json;
using Rookie.CustomerSite.Containts;
using Rookie.CustomerSite.Services.BaseServices;
using RookieShop.Backend.Models;
using RookieShop.Shared;
using RookieShop.Shared.Repo;
using RookieShop.Shared.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;

using X.PagedList;

namespace Rookie.CustomerSite.Controllers
{
    [Route("[controller]")]
    [Authorize]
    public class ProductController : Controller
    {
        // GET: ProductController

        [HttpGet("/product/{id:int}")]
        [AllowAnonymous]
        public async Task<ActionResult> Details(int id)
        {
            ProductDetailsVM productInfo = new ProductDetailsVM();
            
            HttpResponseMessage Res = await RequestServices.GetAsync(APIProductEndPoint.Details + id.ToString());
           
            if (Res.IsSuccessStatusCode)
            {

                var product = Res.Content.ReadAsStringAsync().Result;
               
                productInfo = JsonConvert.DeserializeObject<ProductDetailsVM>(product);
                
                return View(productInfo);
            }
            return View();

        }
        [HttpGet("/ratingproductlist")]
        public async Task<IActionResult> Ratings()
        {
            var accessToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken);
            
            HttpResponseMessage Res = await RequestServices.GetAsync(APIProductEndPoint.Ratings, accessToken);
            
            if (Res.IsSuccessStatusCode)
            {

                var cartResponse = await Res.Content.ReadAsAsync<IEnumerable<ProductListVM>>();
               
                return View(cartResponse);
            }
            TempData["ERROR"] = "ERROR";
           
            return View();
        }
        // Post
        [HttpPost("/ratingproductlist")]

        public async Task<IActionResult> PostRatings(IFormCollection request)
        {

            var id = Convert.ToInt32(request["id"]);
           
            var numberRate = Convert.ToInt32(request[$"stars-{id}"]);

            var accessToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken);
            
            RatingProductRequest rating = new RatingProductRequest()
            {
                ProductId = id,
               
                NumberRating = numberRate,
            };
            
            HttpResponseMessage Res = await RequestServices.PostAsync(APIProductEndPoint.Ratings, accessToken, rating);
            
            if (Res.IsSuccessStatusCode)
            {
                TempData["RATINGS_SUCESS"] = "RATINGS_SUCESS";
                
                return View("Ratings");
            }
            else
            {
                TempData["ERROR"] = "ERROR";
                
                return View("Ratings");
            }

        }

        [AllowAnonymous]
        public async Task<IActionResult> ProductFilter(int? id, string? flag, string? keyword)
        {
            List<ProductListVM> ListProduct = new List<ProductListVM>();
        
            ViewBag.ListCategory = await getListCategory();

            HttpResponseMessage Res = await RequestServices.GetAsync(APIProductEndPoint.GetList);

            if (Res.IsSuccessStatusCode)
            {
                var ProductsResponse = Res.Content.ReadAsStringAsync().Result;
              
                ListProduct = JsonConvert.DeserializeObject<List<ProductListVM>>(ProductsResponse);

            }
            if (!string.IsNullOrEmpty(id.ToString()))
            {
                List<ProductListVM> productsListbyCategoryId = ListProduct.Where(x => x.CategoryId == id).ToList();
               
                return View(productsListbyCategoryId);
            }
            
            if (!string.IsNullOrEmpty(keyword))
            {
                var productsListbyNameProduct = ListProduct.Where(x => x.ProductName.ToUpper().Contains(keyword.ToUpper()));
                
                return View(productsListbyNameProduct);
            }
           
            if (!string.IsNullOrEmpty(flag))
            {
                switch (flag)
                {
                    case "Desc-Name":
                    
                        var productsListbyDescNameProduct = ListProduct.OrderByDescending(x => x.ProductName).ToList();
                        
                        return View(productsListbyDescNameProduct);
                    
                    case "Asc-Name":
                    
                        var productsListbyAscNameProduct = ListProduct.OrderBy(x => x.ProductName).ToList();
                        
                        return View(productsListbyAscNameProduct);
                   
                    case "Desc-Price":
                    
                        var productsListbyDescPrice = ListProduct.OrderByDescending(x => x.UnitPrice).ToList();
                        
                        return View(productsListbyDescPrice);
                   
                    case "Asc-Price":
                    
                        var productsListbyAscPrice = ListProduct.OrderBy(x => x.UnitPrice).ToList();
                        
                        return View(productsListbyAscPrice);
                    
                    default:
                    
                        var list = ListProduct.ToList();
                        
                        return View(list);
                }

            }
            return View(null);
        }

        [HttpGet("/getAllProducts")]
        [AllowAnonymous]
        public async Task<ActionResult> GetAllProduct(int? page)
        {
            List<ProductListVM> ListProduct = new List<ProductListVM>();

            HttpResponseMessage Res = await RequestServices.GetAsync(APIProductEndPoint.GetList);

            if (Res.IsSuccessStatusCode)
            {
                var ProductsResponse = Res.Content.ReadAsStringAsync().Result;
              
                ListProduct = JsonConvert.DeserializeObject<List<ProductListVM>>(ProductsResponse);

            }
            int pageSize = 5;
            
            int pageNumber = (page ?? 1);
            
            var onePageOfProducts = ListProduct.ToPagedList(pageNumber, pageSize);
            
            ViewBag.OnePageOfProducts = onePageOfProducts;
            
            return View();

        }

        [HttpGet("/getListCategory")]
        
        [AllowAnonymous]
        public async Task<List<Category>> getListCategory()
        {

            HttpResponseMessage Res = await RequestServices.GetAsync(APICategoryEndPoint.GetList);
            
            if (Res.IsSuccessStatusCode)
            {
                var list = await Res.Content.ReadAsAsync<IEnumerable<Category>>();

                return list.ToList();
            }
            return null;

        }
    }
}

Rookie.CustomerSite/Views/Product/Details.cshtml
@model RookieShop.Shared.ViewModel.ProductDetailsVM
@{
    ViewData["Title"] = "DetailsAsync";
}
<style>
    .star {
        color: yellow;
        text-decoration: none
    }

        .star:hover {
            color: yellow;
            text-decoration: none;
            pointer-events: none;
        }
</style>

<!-- START HEADING SECTION -->
<div class="about_content">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <div class="product-body">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb text-center text-lg-left">
                            <li class="breadcrumb-item">@*<a href="@Html.ActionLink("Index","Home")">Home</a>*@</li>
                        </ol>
                    </nav>
                    <div class="pro-detail-sec row">
                        <div class="col-12">
                            <h4 class="pro-heading text-center text-lg-left">@Model.ProductName</h4>
                        </div>
                    </div>
                    <div class="row product-list product-detail">

                        <div class="col-12 col-lg-6 product-detail-slider">
                            <div class="wrapper">
                                <div class="Gallery swiper-container img-magnifier-container" id="gallery">
                                    <div class="swiper-wrapper myimgs">
                                        @for (int i = 0; i < Model.PathName.Count; i++)
                                        {
                                            <div class="swiper-slide"> <a href="@Model.PathName[i]" data-fancybox="@i" title="Zoom In"><img class="myimage" src="@Model.PathName[i]" alt="@Model.Alt[i]"></a></div>
                                        }
                                    </div>
                                </div>

                                <div class="Thumbs swiper-container" id="thumbs">
                                    <div class="swiper-wrapper">
                                        @for (int i = 0; i < Model.PathName.Count; i++)
                                        {
                                            <div class="swiper-slide"> <img src="@Model.PathName[i]" alt="thumnails"></div>
                                        }
                                    </div>
                                </div>

                            </div>

                        </div>

                        <div class="col-12 col-lg-6 text-center text-lg-left">
                            <div class="share-product-details">

                                <ul class="user-rating" style="color:yellow">
                                    <li><a href="#" style="color:black">@Model.Rating</a></li>
                                    @for (var i = 1; i <= 5; i++)
                                    {
                                        if (Model.Rating < i)
                                        {
                                            if ((Math.Round(Model.Rating, 1) == i))
                                            {
                                                <li><a href="#" class="star"><i class="lni lni-star-half"></i></a></li>


                                            }
                                            else
                                            {
                                                <li><a href="#" class="star"><i class="lni lni-star"></i></a></li>

                                            }
                                        }
                                        else
                                        {
                                            <li><a href="#" class="star"><i class="lni-star-filled"></i></a></li>
                                        }
                                    }
                                    <li style="color:black">by @Model.UserId.Count() reviewed </li>
                                </ul>
                            </div>
                            <div class="product-single-price">
                                <h4><span class="real-price">@Model.UnitPrice</span> <span></span></h4>
                                <p class="pro-description">Stock:@Model.Stock</p>
                            </div>

                            <div class="product-checklist">
                                <ul>
                                    <li><i class="fas fa-check"></i> Satisfaction 100% Guaranteed</li>
                                    <li><i class="fas fa-check"></i> free shipping on orders over $99</li>
                                    <li><i class="fas fa-check"></i> 14 days easy Return</li>
                                </ul>
                            </div>

                            <div class="row product-quantity input_plus_mins no-gutters" style="background-color:white">
                                @using (Html.BeginForm("Add", "Cart", FormMethod.Post))
                                {
                                    <input type="hidden" name="id" value="@Model.Id" />
                                    <input type="hidden" placeholder="1" value="false" name="isUpdate">
                                    <div class="qty col-12 col-lg-3 d-lg-flex  align-items-lg-center d-inline-block">
                                        <span class="minus bg-dark"><i class="lni-minus"></i></span>
                                        <input type="number" class="count" name="quantity" value="1">
                                        <span class="plus bg-dark"><i class="lni-plus"></i></span>
                                    </div>
                                    <div class="col-12 col-lg-9">
                                        <button type="submit" class="btn btn-warning">ADD TO CART</button>
                                    </div>

                                }
                            </div>

                            <div class="dropdown-divider"></div>

                            <div class="product-tags-list">
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb">
                                        <li class="breadcrumb-item"><p class="d-inline">SKU: <span>@Model.Id</span></p></li>
                                        <li class="breadcrumb-item"><span class="d-inline">Categories:<span class="comma-separtor"></span><a href="@Url.Action("ProductFilter","Product", new { id = Model.CategoryId } )" ">@Model.CategoryName</a></span></li>

                                    </ol>
                                </nav>
                            </div>

                            <div class="share-product-details">
                                <ul class="share-product-icons">
                                    <li><p>Share Link:</p></li>
                                    <li><a href="#" class="facebook-bg-hvr"><i class="fab fa-facebook-f" aria-hidden="true"></i></a></li>
                                    <li><a href="#" class="twitter-bg-hvr"><i class="fab fa-twitter" aria-hidden="true"></i></a> </li>
                                    <li><a href="#" class="linkedin-bg-hvr"><i class="fab fa-linkedin-in" aria-hidden="true"></i></a></li>
                                    <li><a href="#" class="instagram-bg-hvr"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-12 mt-4 mb-4">
                            <div class="row no-gutters product-all-details">

                                <ul class="col-12 nav nav-tabs" id="myTab" role="tablist">
                                    <li class="col-6 nav-item">
                                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Project Description</a>
                                    </li>
                                    <li class="col-6 nav-item">
                                        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Customer Reviews (@Model.UserId.Count)</a>
                                    </li>
                                </ul>
                                <div class="col-12 tab-content" id="myTabContent">
                                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        @Model.Description
                                    </div>
                                    <div class="tab-pane fade reviews" id="contact" role="tabpanel" aria-labelledby="contact-tab">
                                        @if (Model.UserId.Count == 0)
                                        {

                                            <div class="alert alert-info fade show alert-dismissible" role="alert">
                                                <strong><i class="fa fa-info-circle" aria-hidden="true"></i></strong> <b>No Review Yet</b>
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>

                                        }
                                        @for (int i = 0; i < Model.UserId.Count; i++)
                                        {


                                            <span class="text-center text-lg-left d-block">@Model.DateRated[i]</span>
                                            <h5 class="mb-2 text-center text-lg-left">  @Model.UserId[i]</h5>
                                            <p class="text-center text-lg-left">

                                                <ul class="user-rating">
                                                    @for (int j = 0; j < 5; j++)
                                                    {
                                                        if (Model.NumberRating[i] > j)
                                                        {
                                                            <li><a href="#"><i style="color:yellow !important" class="lni-star-filled"></i></a></li>
                                                        }
                                                        else
                                                        {
                                                            <li><a href="#"><i style="color:yellow !important" class="lni lni-star"></i></a></li>
                                                        }

                                                    }
                                                </ul>
                                            </p>




                                        }
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>



</div>

Rookie.CustomerSite/Views/Product/GetAllProduct.cshtml
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@using X.PagedList.Web.Common
@using X.PagedList.Mvc.Bootstrap4

<div class="portfolio-section">
    <div class="container">
        <div class="row">

            <!-- START PORTFOLIO HEADING -->
            <div class="col-12">
                <div class="portfolioHeading text-center">
                    <h1 class="high-lighted-heading">Our Popular Product</h1>
                </div>
            </div>
            <!-- END PORTFOLIO HEADING -->
            <!-- START FILTERS -->
            @await Component.InvokeAsync("CategoryMenu")
        </div>
        <!-- END FILTERS -->
        <!-- START PORTFOLIO IMAGES -->
        <div class="col-12">
            <div id="js-grid-blog-posts" class="cbp">
                @foreach (var item in ViewBag.OnePageOfProducts)
                {
                    <div class="cbp-item Classic Fantasy">
                        <a class="portfolio-circle-cart" href="@Url.Action("AddProduct","Cart", new { id = item.ProductId})">
                            <i class="fa fa-shopping-cart"></i>
                        </a>
                        <div class="img-fluid">
                            <div class="item"> <a href="#" class="cbp-caption" data-fancybox="gallery1" data-title="Book 1"><img src="@item.ImgDefault" alt="#" style="max-height:340px; max-width:340px"></a></div>

                        </div>
                        <div class="row">
                            <div class="col-12 text-center">
                                <div class="cbp-l-grid-blog-title"><a href="@Url.Action("Details","Product",new { id = item.ProductId })" target="_blank" class="portfolio-title">@item.ProductName</a></div>
                            </div>
                            <div class="col-12 text-center">
                                <div class="cbp-l-grid-blog-desc portfolio-des">$ @item.UnitPrice</div>
                            </div>
                        </div>
                    </div>
                }
            </div>
            @Html.PagedListPager((IPagedList)ViewBag.OnePageOfProducts, page => Url.Action("GetAllProduct", new { page }), new X.PagedList.Web.Common.PagedListRenderOptionsBase
       {

           LiElementClasses = new string[] { "page-item" },
           PageClasses = new string[] { "page-link" },

       })
        </div>
        <!-- END PORTFOLIO IMAGES -->

    </div>
</div>
    </div>
<!--START BANNER SECTION-->
<div class="banner-section parallax-slide">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-6 text-center text-lg-left">
                <div class="banner-content-wrapper">
                    <span>TRENDING PRODUCT OF THE WEEK</span>
                    <h1>Books <span>Collections</span></h1>
                    <p>Aenean imperdiet. Etiam ultricies nisi vel augue men tuhi spectrum alle me</p>
                    <button type="button" class="btn green-color-yellow-gradient-btn">BUY NOW</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!--END BANNER SECTION-->
<!--START SEARCH AREA-->
<div class="search-box-overlay">
    <a><i class="fas fa-times cross-sign" id="close-window"></i></a>

    <div class="container">
        <div class="row">
            <div class="col-12 search-col">
                <form action="javascript:void(0)">
                    <div class="input-group search-box-form">
                        <input type="text" class="form-control" placeholder="Search Here" aria-label="Search Here">
                        <div class="input-group-prepend">
                            <button class="input-group-text" type="submit" id="basic-addon1">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>

            <div class="col-12">
                <hr>
            </div>
        </div>
    </div>

</div>
<!--END SEARCH AREA -->

Rookie.CustomerSite/Views/Product/ProductFilter.cshtml
@model IEnumerable<RookieShop.Shared.ViewModel.ProductListVM>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<style>
    .item{
        height:230px!important;
        width:200px!important;
    }
</style>
<!--Product Line Up Start -->
<div class="product-listing">
    <div class="container">
        <div class="row no-gutters">

            <!-- START STICKY NAV -->
            <div class="col-12 col-lg-4 order-2 order-lg-1 sticky">
                <div id="product-filter-nav" class="product-filter-nav mb-3">
                    <div class="product-category">
                        <h5 class="filter-heading  text-center text-lg-left">Category</h5>
                        <ul>
                            @foreach (var i in ViewBag.ListCategory)
                            {

                                <li><a href="@Url.Action("ProductFilter","Product", new { id = i.Id } )"> @i.CategoryName </a><span></span></li>
                            }


                        </ul>
                    </div>

                </div>
            </div>
            <!-- END STICKY NAV -->
            <!-- START PRODUCT COL 8 -->
            <div class="col-md-12 col-lg-8 order-1 order-lg-2">

                <div class="row">

                    <!-- START LISTING HEADING -->
                    <div class="col-12 product-listing-heading">
                        <div class="sort-select-list d-flex ">
                            <label class="mr-2">Sort By:</label>

                            @using (Html.BeginForm("ProductFilter", "Product", FormMethod.Post))
                            {
                                <fieldset>
                                    <select name="flag" id="flag" onchange="this.form.submit()">
                                        <option >Choose</option>
                                        <option value="Asc-Price">Sort by price: low to high</option>
                                        <option value="Desc-Price">Sort by price: high to low</option>

                                    </select>
                                </fieldset>
                            }
                        </div>

                    </div>
                    <!-- END LISTING HEADING -->
                    <!-- START PRODUCT LISTING SECTION -->
                    <div class="col-12 product-listing-products">

                        <!-- START DISPLAY PRODUCT -->
                        <div class="product-list row">

                            @foreach (var item in Model)
                            {
                                <div class="col-12 col-md-6 col-lg-4 manage-color-hover wow slideInUp" data-wow-delay=".2s">
                                    <div class="product-item owl-theme product-listing-carousel owl-carousel">
                                        <div class="item p-item-img">
                                            <img class="img-fluid" src="@item.ImgDefault" alt="images">
                                            <div class="text-center d-flex justify-content-center align-items-center">
                                                <a class="listing-cart-icon" href="@Url.Action("AddProduct","Cart", new { id = item.ProductId})">
                                                    <i class="fa fa-shopping-cart"></i>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="p-item-detail" style="margin-top:20px">
                                        <h4 class="text-center p-item-name"><a href="@Url.Action("Details","Product",new { id = item.ProductId })">@item.ProductName</a></h4>
                                        <p class="text-center p-item-price">$ @item.UnitPrice</p>
                                    </div>
                                </div>

                            }

                        </div>
                        <!-- END DISPLAY PRODUCT -->


                    </div>
                    <!-- END PRODUCT LISTING SECTION -->
                </div>
            </div>
            <!-- END PRODUCT COL 8 -->

        </div>
    </div>
</div>
<!--Product Line Up End-->